require('dotenv').config({ path: '.env.local' });
const { createClient } = require('@supabase/supabase-js');
const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);
async function run() {
  const { error } = await supabase.rpc('execute_sql', { sql: "CREATE TABLE IF NOT EXISTS data_poin_siswa (id bigint generated by default as identity primary key, created_at timestamp with time zone default timezone('utc'::text, now()) not null, tanggal text, kelas text, metadata jsonb);" });
  console.log(error ? error.message : 'Table created');
}
run();
